import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR, Playfair_Display } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import AuthSessionProvider from "@/components/AuthSessionProvider";
import DashboardFloatingButton from "@/components/DashboardFloatingButton";
import { TutorialMission } from "@/components/TutorialMission";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansKr = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSansKr.variable} ${playfairDisplay.variable} antialiased`}
        style={{ fontFamily: 'var(--font-noto-sans-kr), system-ui, sans-serif' }}
      >
        <AuthSessionProvider session={session}>
          {children}
        </AuthSessionProvider>
        <DashboardFloatingButton />
        <TutorialMission />
      </body>
    </html>
  );
}
